version: '3.8'

services:
  frontend:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=PROD
      - ENVIRONMENT=PROD
      - SQLALCHEMY_DATABASE_URI=postgresql://myuser:mypassword@postgres:5432/mydb
    command: >
      sh -c "flask db upgrade && gunicorn wsgi:app -b 0.0.0.0:8080 --log-file=- --access-logfile=-"

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
