version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    networks:
      - app-network
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.25
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
