"""change quant columns

Revision ID: 40353cf50d94
Revises: fd224dda2176
Create Date: 2024-10-14 21:32:05.062671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40353cf50d94'
down_revision = 'fd224dda2176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('initial_trend_follow', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('initial_status', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('current_status', sa.String(length=10), nullable=False))
        batch_op.alter_column('quant_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quant', schema=None) as batch_op:
        batch_op.alter_column('quant_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('current_status')
        batch_op.drop_column('initial_status')
        batch_op.drop_column('initial_trend_follow')
        batch_op.drop_column('initial_price')

    # ### end Alembic commands ###
