"""ADD user table app_token column

Revision ID: 4eba8f8480bd
Revises: 40353cf50d94
Create Date: 2024-10-18 21:28:07.722599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eba8f8480bd'
down_revision = '40353cf50d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('app_token')

    # ### end Alembic commands ###
