"""DEL last_current_status column

Revision ID: a9e4c6c8d2b1
Revises: 1cbb1f31cb7a
Create Date: 2024-11-08 20:44:37.267986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e4c6c8d2b1'
down_revision = '1cbb1f31cb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quant', schema=None) as batch_op:
        batch_op.drop_column('last_send_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_send_status', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
