# .github/workflows/test.yml
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "SQLALCHEMY_DATABASE_URI=sqlite:///test.db" >> backend/.env
          echo "JWT_SECRET_KEY=your_test_secret_key" >> backend/.env

      - name: Run tests
        working-directory: backend
        run: pytest tests/

